#!/bin/bash
# (C) tim.menzies@gmail.com 2016, http://unlicense.org/

# My favorite repo trick
# Avoids have Makefiles all over the sub-directories.
# Calls to "make" jump to  root of current repo, and "makes" there.

# usage:  . hi

make1() {
  if [ ! -f Makefile ]; then
    echo "nothing to do"
  else
    /usr/bin/make $* 
  fi
}

make() {
  root=$(git rev-parse --show-toplevel)
  if [ -n "$root" ]; then
    ( cd $root; make1 $*)
  else
    /usr/bin/make $*
  fi
}
